config/routes.rb
Rails.application.routes.draw do
  resources :clucks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root "clucks#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cluck.rb
class Cluck < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clucks_controller.rb
class ClucksController < ApplicationController
  before_action :set_cluck, only: %i[ show edit update destroy ]

  # GET /clucks or /clucks.json
  def index
    @clucks = Cluck.all
  end

  # GET /clucks/1 or /clucks/1.json
  def show
  end

  # GET /clucks/new
  def new
    @cluck = Cluck.new
  end

  # GET /clucks/1/edit
  def edit
  end

  # POST /clucks or /clucks.json
  def create
    @cluck = Cluck.new(cluck_params)

    respond_to do |format|
      if @cluck.save
        format.html { redirect_to @cluck, notice: "Cluck was successfully created." }
        format.json { render :show, status: :created, location: @cluck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cluck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clucks/1 or /clucks/1.json
  def update
    respond_to do |format|
      if @cluck.update(cluck_params)
        format.html { redirect_to @cluck, notice: "Cluck was successfully updated." }
        format.json { render :show, status: :ok, location: @cluck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cluck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clucks/1 or /clucks/1.json
  def destroy
    @cluck.destroy
    respond_to do |format|
      format.html { redirect_to clucks_url, notice: "Cluck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cluck
      @cluck = Cluck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cluck_params
      params.require(:cluck).permit(:cluck)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clucks_helper.rb
module ClucksHelper
end

app/views/clucks/_form.html.erb
<%= form_with(model: cluck) do |form| %>
  <% if cluck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cluck.errors.count, "error") %> prohibited this cluck from being saved:</h2>

      <ul>
        <% cluck.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cluck %>
    <%= form.text_area :cluck %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clucks/edit.html.erb
<h1>Editing Cluck</h1>

<%= render 'form', cluck: @cluck %>

<%= link_to 'Show', @cluck %> |
<%= link_to 'Back', clucks_path %>

app/views/clucks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clucks</h1>

<table>
  <thead>
    <tr>
      <th>Cluck</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clucks.each do |cluck| %>
      <tr>
        <td><%= cluck.cluck %></td>
        <td><%= link_to 'Show', cluck %></td>
        <td><%= link_to 'Edit', edit_cluck_path(cluck) %></td>
        <td><%= link_to 'Destroy', cluck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cluck', new_cluck_path %>

app/views/clucks/new.html.erb
<h1>New Cluck</h1>

<%= render 'form', cluck: @cluck %>

<%= link_to 'Back', clucks_path %>

app/views/clucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cluck:</strong>
  <%= @cluck.cluck %>
</p>

<%= link_to 'Edit', edit_cluck_path(@cluck) %> |
<%= link_to 'Back', clucks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Henhouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>